name: Joyla Tracker

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */4 * * *'

permissions:
  contents: write

jobs:
  tracker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests

      - run: python joyla.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Commit last release
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last_release.txt
          git commit -m "update last release" || exit 0
          git push
